files:
  Kotshi.kt:
      folder: src/main/kotlin/org/openapitools/server
  routes.mustache:
      folder: src/main/kotlin/org/openapitools/server/apis
      destinationFilename: Routes.kt
  auth.mustache:
      folder: src/main/kotlin/org/openapitools/server/apis
      destinationFilename: Auth.kt