on: [push]

concurrency:
  group: ${{ github.ref }}

jobs:
  aws_cdk:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run build with Gradle Wrapper
        run: |
          cd lambdas
          ./gradlew build
      - name: Run test with Gradle Wrapper
        run: |
          cd lambdas
          ./gradlew test
      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: npm pull contract
        run: |
          cd cdk
          npm run pullApiSpec
      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "synth"
          working_dir: 'cdk'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-2"
          CDK_ACCOUNT_ID: ${{ secrets.CDK_ACCOUNT_ID }}
          CDK_DB_PASSWORD: ${{ secrets.CDK_DB_PASSWORD }}
      - name: cdk deploy
        if: github.ref == 'refs/heads/main'
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "deploy"
          cdk_args: "--require-approval never"
          working_dir: 'cdk'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-2"
          CDK_ACCOUNT_ID: ${{ secrets.CDK_ACCOUNT_ID }}
          CDK_DB_PASSWORD: ${{ secrets.CDK_DB_PASSWORD }}